language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: osx
      osx_image: xcode7.3
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sudo easy_install nose;
    fi
  - pip install -r requirements.txt

script: 
  - python setup.py build_ext --inplace
  - nosetests -s -v
